### ISSUE TITLE
請問要如何編譯??

### ISSUE THREAD

**Issue by kay54068** [redxu/sihook#1]
請問要如何編譯??
要使用哪個Complier?

**Comment by redxu** [comment]
请看Readme
可以直接用CodeBlocks工具编译
也可以用mingw-gcc手工编译

**Comment by kay54068** [comment]
我用mingw-gcc 產出的dll檔，有以下錯誤:
![image](https://cloud.githubusercontent.com/assets/3054544/16725787/768700b0-478b-11e6-96df-71d084d05ee9.png)

**Comment by redxu** [comment]
1,gcc默认编译是动态链接libgcc库,可以把这个dll拷贝到程序目录(在MinGW/bin目录下)
2,或者编译的时候加上参数-static-libgcc可以去掉libgcc_s_dw2-1.dll这个小尾巴
有些gcc版本(TDM)默认是静态编译的

**Comment by kay54068** [comment]
謝謝您~，您真厲害，可以成功運行

請問我在make 的時候遇到以下warrinhg 是為何??

patch.c: In function 'PatchSI':
patch.c:23:17: warning: initialization from incompatible pointer type [enabled b
y default]
patch.c:40:38: warning: comparison of distinct pointer types lacks a cast [enabl
ed by default]
![image](https://cloud.githubusercontent.com/assets/3054544/16732636/bf5e8b44-47b0-11e6-9efa-beb4c6ad389e.png)

**Comment by kay54068** [comment]
請問您sihook 有支援64 bit 的作業系統嗎?

**Comment by redxu** [comment]
编译的warning是因为有个类型的强制转换.patch.c line23: PBYTE exemod = GetModuleHandle(NULL);
GetModuleHandle的返回类型是HMODULE 而右侧类型是PBYTE,编译器在编译的时候检测到类型不一致会给一个警告.当然也推荐加上强制转换类型来消除这个警告.

**Comment by redxu** [comment]
SourceInsight3是32 bit的程序,sihook也是用32 bit gcc进行编译的.
在x86/x64位系统下都是可以运行使用的.
但是有些版本的windows系统,使用msimg32是无法引导sihook.dll文件的.因此在这种情况下,我做了另外一个loader工具来引导sihook.dll `[地址](https://github.com/redxu/siutf8/tree/master/siloaderex)`

**Comment by kay54068** [comment]
謝謝您，已解決可以編譯使用。

**Comment by kay54068** [comment]
請問一下siutf8 專案中的 loaderdll.dll 的Source 是 hookapi 編譯出的嗎?

**Comment by redxu** [comment]
eee,loaderdll.dll的源码丢失了...
