### ISSUE TITLE
msimg32.dll不加载

### ISSUE THREAD

**Issue by bensonfx** [redxu/sihook#2]
win10 x64,使用procmon.exe使用追踪加载的dll，
1.发现msimg32.dll,放在程序目录下，还是加载的%windir%\syswow64目录下的msimg32.dll.
2.查看了加载的其他dll,发现version.dll,
3.网上找了一个hook代码，但是insight3.exe.看到任何UI界面，追踪发现sihook.dll使用成功加载，
4.去掉version.dll的加载sihook.dll,，也就等于只是hook了version.dll,这个时候程序一切正常。

功力不够，希望能给作者一下参考，看看是否能改成其他的hook方式。

**Comment by redxu** [comment]
有些版本的windows系统,使用msimg32是无法引导sihook.dll文件的.因此在这种情况下,我做了另外一个loader工具来引导sihook.dll [地址](https://github.com/redxu/siutf8/tree/master/siloaderex)
貌似大多数win10 x64无法用msimg32引导

**Comment by bensonfx** [comment]
1.我现在用的也是loader的方式，但相对而言，还是hook的方式，更方便一点。
2.说明一下，我的是win10 x64,只用了系统自带的杀软 windows denfender。查了knownDLL，并没有将msimg32.dll,
3.之前有一个电脑的win10,在很偶尔的情况下可以加载msimg32.dll，关闭再次打开即失败。
换了几个电脑装source insight，所以觉得msimg32 hook失败还是挺普遍的。

但version.dll，或者其他dll的hook，我觉得还是可行的。但对方面研究有限，
如果能的话，还是希望能够有用hook的方式，毕竟这样更方便，不知redxu兄能否研究一下version.dll的dll

1.version.dll的参考：
http://www.chinapyg.com/thread-74879-1-1.html

**Comment by redxu** [comment]
version.dll研究过,导出的函数也不多,有空做个模板试试

**Comment by bensonfx** [comment]
另一份version.dll hook的参考源码：http://www.dllhook.com/post/6.html
那就期待redxu出新的版本了。

**Comment by redxu** [comment]
用hook引导方式对dll的加载时机有要求,必须在user32加载完成后加载(即延时加载的dll)
version.dll不属于这种,会导致引导出错.
符合条件的几个dll:comctl32,uxtheme,shell32,msimg32. msimg32导出函数是最少的.

**Comment by bensonfx** [comment]
原来如此，我说sihook已经起来了，但是UI就是起不来。原因原来在这里。
多谢redxu~~

**Comment by bensonfx** [comment]
关于导出函数较的时候的处理，看出greenchome winimm的处理，是使用获取系统dll的PE Header结构体。@redxu兄可以参考下。

**Comment by melonshell** [comment]
win10 X64一直加载不成功，有方法没

**Comment by ParticleG** [comment]
经测试，有其他使用`msimg32.dll`的程序已经在运行时，好像会影响SourceInsight加载msimg32.dll的查找优先级。目前发现搜狗和百度输入法会导致这个问题
