### ISSUE TITLE
popupmenu 新增功能

### ISSUE THREAD

**Issue by kay54068** [redxu/sihook#3]
請問一下，若我要在popupmenu ITEM 中 加上"開啟檔案所在目錄並指向該檔案的功能"要如何實現??

**Comment by redxu** [comment]
不好实现,因为用sihook里能得到的信息只有标题和内部窗口句柄,没有目录或者全路径的相关信息.
不过有个思路可以尝试.
1,借助siutf8,在里面增加一个接口,通过标题查找路径(参考FindU8FlagFromLink).调用代码可以参考V1.2alpha
